name: dockeraction

description: calculator to test container action

inputs:
  number1:
    required: true
    default: "0"

  number2:
    required: true
    default: "0"

outputs:
  result:
    description: Sum of two numbers

runs:
  using: docker
  image: Dockerfile

  args:
    - ${{ inputs.number1 }}
    - ${{ inputs.number2 }}
